# Generated by Django 3.1 on 2021-11-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='puerto',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
