# Generated by Django 3.1 on 2021-11-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('tipo', models.CharField(choices=[('Ordenador', 'Ordenador'), ('Raspi', 'Raspi'), ('Placa', 'Placa'), ('Sensor', 'Sensor'), ('Actuador', 'Actuador')], max_length=1000)),
                ('ip', models.GenericIPAddressField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
