name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: websockets-app-env
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Configuración de Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalar dependencias y pasar test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SECRET_ECHO: ${{ secrets.SECRET_ECHO }}
      run: |
        echo "Comenzando las tareas de testing y despliegue"
        echo "${{ env.SECRET_KEY }}"
        echo "${{ secrets.SECRET_KEY }}"
        echo "${{ secrets.SECRET_ECHO }}"
        echo  "${{ env.SECRET_ECHO }}"
        cd app
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt
        python manage.py test
